### ISSUE TITLE
S3 does not work with AWS Instance Roles

### ISSUE THREAD

**Issue by awm33** [RaRe-Technologies/smart_open#122] opened 2017-04-28 05:10 UTC
Since this uses an old version of boto, it will not load instance role credentials, making it unusable in a typical AWS production environment,

**Comment by tmylk** [comment] 2017-05-03 00:44
Thanks for reporting it. What is a good new version of boto to use?
Do you have a code snipped to reproduce?

**Comment by piskvorky** [comment] 2017-05-03 01:36
@tmylk that's issue #43 , I believe.

If boto3 is finally production ready now (is it?), we should definitely switch.

**Comment by vinuthna91** [comment] 2017-06-01 10:36
Hi for me I see data corruption while writing to a avro on S3. Is it expected?

**Comment by menshikh-iv** [comment] 2017-12-13 06:41
duplicate of #43 (need to move to `boto3`)

**Closed by menshikh-iv** 2017-12-13 06:41 UTC
Labels: enhancement, medium difficult
