### ISSUE TITLE
Enhancement request: support file size operation

### ISSUE THREAD

**Issue by davidparks21** [RaRe-Technologies/smart_open#504] opened 2020-05-30 23:24 UTC
#### Problem description
There doesn't appear to be any way to get file size using `smart_open`. Adding a function to return this very common file operation seems reasonable because it's such an integral part of streaming operations.

For example, implementing `__len__` would be a nice way to do it, such that `len(open('s3://bucket/path/file', 'rb'))` returns the file size, it doesn't seem like that would add much complexity and would be a significant enhancement.

#### Versions
```
Linux-4.15.0-99-generic-x86_64-with-debian-buster-sid
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
smart_open 1.9.0
```

#### Checklist

Before you create the issue, please make sure you have:

- [X] Described the problem clearly
- [NA] Provided a minimal reproducible example, including any required data
- [X] Provided the version numbers of the relevant software

**Comment by petedannemann** [comment] 2020-05-31 15:23
Possible duplicate of https://github.com/RaRe-Technologies/smart_open/issues/499

Not all transport mechanisms support this feature, but all of the cloud ones should by accessing the underlying blob / object. S3 supports this explicitly with the `to_boto3` method https://github.com/RaRe-Technologies/smart_open/blob/688ea0956e8aa85d566d286874b02e106a2c0d4e/smart_open/s3.py#L515.

```python
from smart_open import open

with open('s3://mybucket/mykey') as f:
    s3_obj = f.to_boto3() # type: boto3.s3.Object
    size = s3_obj.content_length
```

**Closed** 2020-05-31 19:45 UTC
