### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by ba1dr** [RaRe-Technologies/smart_open#86] opened 2016-08-01 20:42 UTC
I am receiving an error each time when I try to upload a large stream (not just file):

    [2016-08-01 20:13:48,253: ERROR/Worker-4] encountered error while terminating multipart upload; attempting cancel
    Traceback (most recent call last):
      File "/opt/mypath/myapp/apps/lib/awsutils/s3stream.py", line 21, in bucket_put_stream
        fout.write(buffer)
      File "/opt/mypath/venv/lib/python3.4/site-packages/smart_open/smart_open_lib.py", line 487, in write
        self.mp.upload_part_from_file(BytesIO(buff), part_num=self.parts + 1)
      File "/opt/mypath/venv/lib/python3.4/site-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
        query_args=query_args, size=size)
      File "/opt/mypath/venv/lib/python3.4/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
        chunked_transfer=chunked_transfer, size=size)
      File "/opt/mypath/venv/lib/python3.4/site-packages/boto/s3/key.py", line 750, in send_file
        chunked_transfer=chunked_transfer, size=size)
      File "/opt/mypath/venv/lib/python3.4/site-packages/boto/s3/key.py", line 951, in _send_file_internal
        query_args=query_args
      File "/opt/mypath/venv/lib/python3.4/site-packages/boto/s3/connection.py", line 668, in make_request
        retry_handler=retry_handler
      File "/opt/mypath/venv/lib/python3.4/site-packages/boto/connection.py", line 1071, in make_request
        retry_handler=retry_handler)
      File "/opt/mypath/venv/lib/python3.4/site-packages/boto/connection.py", line 1030, in _mexe
        raise ex
      File "/opt/mypath/venv/lib/python3.4/site-packages/boto/connection.py", line 940, in _mexe
        request.body, request.headers)
      File "/opt/mypath/venv/lib/python3.4/site-packages/boto/s3/key.py", line 844, in sender
        http_conn.send(chunk)
      File "/usr/lib/python3.4/http/client.py", line 888, in send
        self.sock.sendall(data)
      File "/usr/lib/python3.4/ssl.py", line 741, in sendall
        v = self.send(data[count:])
      File "/usr/lib/python3.4/ssl.py", line 702, in send
        v = self._sslobj.write(data)
    ConnectionResetError: [Errno 104] Connection reset by peer

The error is thrown by `boto`, so the issue might be related to https://github.com/boto/boto/issues/2207 . I tried all workarounds, but no luck.

My code looks like this:

    def bucket_put_stream(stream, bucket, key):
        awskey = AWS_SETTINGS['AWS']['ACCESS_KEY_ID']
        awssecret = AWS_SETTINGS['AWS']['SECRET_ACCESS_KEY']
        size = 0
        with smart_open.smart_open('s3://%s:%s@%s/%s' % (awskey, awssecret, bucket, key), 'wb') as fout:
            for data in stream:
                fout.write(data)
                size += len(data)
        return size

Small file of 17Kb was uploaded without issues, so the problem shouldn't be in permissions.

**Comment by ba1dr** [comment] 2016-08-01 21:22
Hmm, it seems the issue went away after some time.
I can recommend this SO answer: http://stackoverflow.com/a/23397672/494631
It seems 'training' S3 does make sense. I cannot explain it otherwise.

**Comment by tmylk** [comment] 2016-08-02 17:44
Thanks for reporting it. Closing it as "can't reproduce".

**Closed** 2016-08-02 17:43 UTC

**Comment by dribler** [comment] 2018-02-26 12:31
@ba1dr u probably exceeded maximum number of parts allowed on multipart upload
