### ISSUE TITLE
Support buckets with "." in the name

### ISSUE THREAD

**Issue by AndreaCrotti** [RaRe-Technologies/smart_open#52] opened 2016-01-11 19:15 UTC
It's not exactly related to smart_open but it currently suffers from this issue as well, opening any key dots in the bucket name generate this error below:

```python

    smart_open.smart_open('s3://bucket.name.with.dots/full/path/to/key')
    
    /home/andrea/.virtualenvs/cookie-sync-processing/lib/python2.7/site-packages/smart_open/smart_open_lib.pyc in smart_open(uri, mode, **kw)
        120         elif parsed_uri.scheme in ("s3", "s3n"):
        121             s3_connection = boto.connect_s3(aws_access_key_id=parsed_uri.access_id, aws_secret_access_key=parsed_uri.access_secret)
    --> 122             bucket = s3_connection.get_bucket(parsed_uri.bucket_id)
        123             if mode in ('r', 'rb'):
        124                 key = bucket.get_key(parsed_uri.key_id)
    
    /home/andrea/.virtualenvs/cookie-sync-processing/lib/python2.7/site-packages/boto/s3/connection.pyc in get_bucket(self, bucket_name, validate, headers)
        500         """
        501         if validate:
    --> 502             return self.head_bucket(bucket_name, headers=headers)
        503         else:
        504             return self.bucket_class(self, bucket_name)
    
    /home/andrea/.virtualenvs/cookie-sync-processing/lib/python2.7/site-packages/boto/s3/connection.pyc in head_bucket(self, bucket_name, headers)
        519         :returns: A <Bucket> object
        520         """
    --> 521         response = self.make_request('HEAD', bucket_name, headers=headers)
        522         body = response.read()
        523         if response.status == 200:
    
    /home/andrea/.virtualenvs/cookie-sync-processing/lib/python2.7/site-packages/boto/s3/connection.pyc in make_request(self, method, bucket, key, headers, data, query_args, sender, override_num_retries, retry_handler)
        662             data, host, auth_path, sender,
        663             override_num_retries=override_num_retries,
    --> 664             retry_handler=retry_handler
        665         )
    
    /home/andrea/.virtualenvs/cookie-sync-processing/lib/python2.7/site-packages/boto/connection.pyc in make_request(self, method, path, headers, data, host, auth_path, sender, override_num_retries, params, retry_handler)
       1069                                                     params, headers, data, host)
       1070         return self._mexe(http_request, sender, override_num_retries,
    -> 1071                           retry_handler=retry_handler)
       1072 
       1073     def close(self):
    
    /home/andrea/.virtualenvs/cookie-sync-processing/lib/python2.7/site-packages/boto/connection.pyc in _mexe(self, request, sender, override_num_retries, retry_handler)
        941                 else:
        942                     connection.request(request.method, request.path,
    --> 943                                        request.body, request.headers)
        944                     response = connection.getresponse()
        945                 boto.log.debug('Response headers: %s' % response.getheaders())
    
    /usr/lib/python2.7/httplib.pyc in request(self, method, url, body, headers)
       1050     def request(self, method, url, body=None, headers={}):
       1051         """Send a complete request to the server."""
    -> 1052         self._send_request(method, url, body, headers)
       1053 
       1054     def _set_content_length(self, body, method):
    
    /usr/lib/python2.7/httplib.pyc in _send_request(self, method, url, body, headers)
       1090         for hdr, value in headers.iteritems():
       1091             self.putheader(hdr, value)
    -> 1092         self.endheaders(body)
       1093 
       1094     def getresponse(self, buffering=False):
    
    /usr/lib/python2.7/httplib.pyc in endheaders(self, message_body)
       1046         else:
       1047             raise CannotSendHeader()
    -> 1048         self._send_output(message_body)
       1049 
       1050     def request(self, method, url, body=None, headers={}):
    
    /usr/lib/python2.7/httplib.pyc in _send_output(self, message_body)
        890             msg += message_body
        891             message_body = None
    --> 892         self.send(msg)
        893         if message_body is not None:
        894             #message_body was not a string (i.e. it is a file) and
    
    /usr/lib/python2.7/httplib.pyc in send(self, data)
        852         if self.sock is None:
        853             if self.auto_open:
    --> 854                 self.connect()
        855             else:
        856                 raise NotConnected()
    
    /usr/lib/python2.7/httplib.pyc in connect(self)
       1271 
       1272             self.sock = self._context.wrap_socket(self.sock,
    -> 1273                                                   server_hostname=server_hostname)
       1274 
       1275     __all__.append("HTTPSConnection")
    
    /usr/lib/python2.7/ssl.pyc in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname)
        350                          suppress_ragged_eofs=suppress_ragged_eofs,
        351                          server_hostname=server_hostname,
    --> 352                          _context=self)
        353 
        354     def set_npn_protocols(self, npn_protocols):
    
    /usr/lib/python2.7/ssl.pyc in __init__(self, sock, keyfile, certfile, server_side, cert_reqs, ssl_version, ca_certs, do_handshake_on_connect, family, type, proto, fileno, suppress_ragged_eofs, npn_protocols, ciphers, server_hostname, _context)
        577                         # non-blocking
        578                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
    --> 579                     self.do_handshake()
        580 
        581             except (OSError, ValueError):
    
    /usr/lib/python2.7/ssl.pyc in do_handshake(self, block)
        814                 raise ValueError("check_hostname needs server_hostname "
        815                                  "argument")
    --> 816             match_hostname(self.getpeercert(), self.server_hostname)
        817 
        818     def _real_connect(self, addr, connect_ex):
    
    /usr/lib/python2.7/ssl.pyc in match_hostname(cert, hostname)
        269         raise CertificateError("hostname %r "
        270             "doesn't match either of %s"
    --> 271             % (hostname, ', '.join(map(repr, dnsnames))))
        272     elif len(dnsnames) == 1:
        273         raise CertificateError("hostname %r "
    
    CertificateError: hostname 'bucket.with.dots' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'

```

In our projects we worked around this just by doing this (the calling_format), I think we could the same in smart_open:

```python
    return S3Connection(
        AWS_ACCESS_KEY,
        AWS_SECRET_ACCESS_KEY,
        validate_certs=True,
        # necessary to workaround the extra security introduced
        calling_format=OrdinaryCallingFormat(),
    )
```

**Comment by tmylk** [comment] 2016-10-05 06:27
Duplicate of #26

**Closed by tmylk** 2016-10-05 06:27 UTC
Labels: medium difficult, wishlist
