### ISSUE TITLE
importing gensim issue

### ISSUE THREAD

**Issue by sanjaycode** [RaRe-Technologies/smart_open#480] opened 2020-04-23 20:43 UTC
#### I installed gensim using (pip install gensim) and it installed successfully:

`Successfully installed boto-2.49.0 boto3-1.12.45 botocore-1.15.45 docutils-0.15.2 gensim-3.8.2 jmespath-0.9.5 s3transfer-0.3.3 smart-open-1.11.1`

#### but now if I am trying to import it in my jupyter notebook, its showing this error:
`unable to import 'smart_open.gcs', disabling that module`

![Capture](https://user-images.githubusercontent.com/48735826/80147359-06fb1a00-85d1-11ea-9eca-11efbb36ae1c.JPG)

How to resolve?

**Comment by mpenkov** [comment] 2020-04-24 00:46
This is a duplicate of https://github.com/RaRe-Technologies/smart_open/issues/475. Please see the discussion in that ticket.

**Closed by mpenkov** 2020-04-24 00:46 UTC
