### ISSUE TITLE
error: Error -3 while decompressing: incorrect header check

### ISSUE THREAD

**Issue by yg37** [RaRe-Technologies/smart_open#108] opened 2017-03-10 19:34 UTC
I was trying to read a compressed file from s3 on ec2 and it did not print any line
```python
for myKey,content in smart_open.s3_iter_bucket(email_bucket):
    with smart_open.smart_open(myKey) as data:
        for line in data:
            print line
```

Then I ran:
```python
file = smart_open.smart_open(myKey)
for line in data:
    print line
```
and got the error: 
<img width="677" alt="screen shot 2017-03-10 at 11 33 25 am" src="https://cloud.githubusercontent.com/assets/13965488/23810186/6602dc10-0585-11e7-99fb-056f3141c36f.png">

I think this is caused by zlib. Any insight on how to troubleshoot this?

**Comment by tmylk** [comment] 2017-03-17 16:38
Does the file have a correct header? Can you unpack it using command line?

**Comment by mpenkov** [comment] 2017-12-10 06:53
@yg37 Are you still experiencing this problem?

**Comment by menshikh-iv** [comment] 2017-12-13 06:31
I can't reproduce it (because have problem with `boto`)
```
S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>AB8655982527167A</RequestId><HostId>Nn9fq1Vwhn4nwnCrPcLEl8EaL1NqAH4GRSOUiYFIxJ8jf7vX4QFLkBMYYVOQmRfXpMtLjLmjUtE=</HostId></Error>
```

Need to move `s3_iter_bucket` to `boto3` and check again, related issue #43

**Comment by yg37** [comment] 2017-12-13 17:45
I think I solved the issue by modifying the `s3_iter_bucket` function and using `list(smart_open.S3Openead(key))`.

**Comment by mpenkov** [comment] 2018-10-01 13:49
@menshikh-iv Looks like we can close this. We can't really do anything without access to the offending file, and the user seems to have found a work-around.

**Comment by menshikh-iv** [comment] 2018-10-02 04:11
yes, let's close it @mpenkov

**Closed by menshikh-iv** 2018-10-02 04:11 UTC
