### ISSUE TITLE
uploading failed while dealing with empty file 

### ISSUE THREAD

**Issue by amolsaudar123** [RaRe-Technologies/smart_open#308] opened 2019-04-23 13:32 UTC
Hi,
  Currently I am using smart_open library.But I am facing an issue related with empty file .while it is working well with any file but when I deal with any empty file it throws me exceptions
Like 
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
can you please Help me out how can I Deal with empty file in smart_open

**Comment by amolsaudar123** [comment] 2019-04-23 13:36
![c1](https://user-images.githubusercontent.com/29245705/56585099-c8680380-65fa-11e9-8c61-949e1f32b3f9.PNG)
![c2](https://user-images.githubusercontent.com/29245705/56585101-c8680380-65fa-11e9-98c6-48c94d26122b.PNG)
Here is the snippet ,where in one file I have some data in test2 ,but in test1 we dont have any data ,so in test1 to upload it to s3 it gives me botocore.exception

**Comment by mpenkov** [comment] 2019-04-23 23:08
From the screenshots you are posting, the operation is failing because of an "Access Denied" error.

I can confirm that writing empty files to S3 works with smart_open 3.8.2 and the below code:

```python
(smart_open) misha@cabron:~/git/smart_open$ ipython
Python 3.6.5 (default, Apr  1 2018, 05:46:30)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from smart_open import open

In [2]: with open('s3://bucket/test_smart_open/empty', 'w') as fout:
   ...:     pass

In [3]: with open('s3://bucket/test_smart_open/empty', 'r') as fin:
   ...:     print(repr(fin.read()))
''
```

What version of smart_open are you using?

**Comment by amolsaudar123** [comment] 2019-04-24 08:33
How do  know smart_open version?
can you please help me out

**Comment by mpenkov** [comment] 2019-04-24 08:43
Run `pip show smart-open`

**Comment by MMMohit** [comment] 2019-04-24 08:48
Hi I am facing issue related with empty file,during uploading from hdfs to s3 .whenever I upload any non empty file its uploaded successfully on s3 ,but once I deal with any empty file it gives me exception like 
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

and also can you just help me out with smart_open version? How can I know about it using cli
an also I have used code as its snippet is 
for line in smart_open(hdfs_path, encoding='utf8'):
					#with open(my_file) as friendsfile:
							if not line:
								logging.info('Writing lines into "s3://car-test-s3-consumptionbucket/test.csv"....')
								fout.write(line)
								#print('friendsfile is empty !!')
							else:
								#print(" file is not empty!!!")
								continue

**Comment by mpenkov** [comment] 2019-04-24 08:58
I've tried to reproduce the problem on my end, unsuccessfully (see my first comment). I'd like to help you, but your recent comment provides absolutely no new information to me.

In order for me to be able to help you, I need to know more information:

1. The smart_open version (see my reply above for methods of getting it)
2. A **full** stack trace (copy paste). You've provided me some screenshots, but they aren't helpful (one of them is a Java stack trace completely unrelated to smart_open).
3. A **reproducible example** of the problem code. Ideally, this should be something I can simply run on my side to reproduce the problem. Make this sample as small as possible: remove all irrelevant parts. In your case, reading from HDFS is likely unrelated. For an example, see my first comment.

As a side question, does the following work for you?

```python
from smart_open import open
with open('s3://bucket/test_smart_open/empty', 'w') as fout:
     pass  # write empty file
with open('s3://bucket/test_smart_open/empty', 'r') as fin:
     print(repr(fin.read()))  # read empty file back
```

(obviously, replace `bucket` with your actual S3 bucket name).

**Comment by MMMohit** [comment] 2019-04-24 09:12
smart_open version i s
1.8.0
 here is the code snip
![sv1](https://user-images.githubusercontent.com/30354328/56647462-20f0dc80-669f-11e9-91a0-64b5bc9fdafe.PNG)

**Comment by mpenkov** [comment] 2019-04-24 09:36
Try installing the newest version of smart_open (1.8.2).

Alternatively, try `from smart_open import smart_open as open` instead.

**Comment by MMMohit** [comment] 2019-04-24 09:50
Yes it works for me thanks but after running this code I got output as a

u' '
what is meaning of this output ?

and here is the code 
from smart_open import smart_open as open
hdfs_path='hdfs://user/mohitm/sagar/test1.csv'
with open(hdfs_path, 'r') as fin:
    print(repr(fin.read()))

**Comment by mpenkov** [comment] 2019-04-24 10:02
From this discussion, it is obvious to me that there is no bug in this case, so I'm closing the ticket.

If you have further questions, then the more appropriate place to ask them is stackoverflow.com.

**Closed by mpenkov** 2019-04-24 10:02 UTC
Labels: need-info, question
