### ISSUE TITLE
inconsistent with bz2.open on files containing vertical tab ^K

### ISSUE THREAD

**Issue by yunjiangster** [RaRe-Technologies/smart_open#394] opened 2019-11-30 05:54 UTC
#### Problem description

Be sure your description clearly answers the following questions:

- What are you trying to achieve?
Trying to use smart_open to replace bz2.open
- What is the expected result?
same behavior as bz2.open wrt recognizing line breaks
- What are you seeing instead?
a long line got truncated due to the presence of non-line break symbol ^K

#### Steps/code to reproduce the problem

In order for us to be able to solve your problem, we have to be able to reproduce it on our end.
Without reproducing the problem, it is unlikely that we'll be able to help you.

Include full tracebacks, logs and datasets if necessary.
Please keep the examples minimal ([minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)).

take for instance the following binary uncompressed text. compress with bz2. The numbers of columns before and after bz2 as recognize with smart_open(..).readline() are different.

\xe5\x93\x81\x0b\xe3\x80\n

#### Versions

Please provide the output of:

```python
import platform, sys, smart_open
print(platform.platform())
print("Python", sys.version)
print("smart_open", smart_open.__version__)
```
>>> print("smart_open", smart_open.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'smart_open' has no attribute '__version__'

Instead

pip show smart_open
Name: smart-open
Version: 1.7.1

#### Checklist

Before you create the issue, please make sure you have:

- [x] Described the problem clearly
- [ ] Provided a minimal reproducible example, including any required data
- [x] Provided the version numbers of the relevant software

**Comment by yunjiangster** [comment] 2019-11-30 05:59
Tried with 1.9.0 as well and same problem.

with smart_open.smart_open('debug.tsv.bz2', mode='r') as f:
...     tmp = f.readline().strip('\r\n').split('\t')
>>> len(tmp)
444

with smart_open.smart_open('debug.tsv', mode='r') as f:
...     tmp = f.readline().strip('\r\n').split('\t')
>>> len(tmp)
852

with open('debug.tsv', mode='r') as f:
...     tmp = f.readline().strip('\r\n').split('\t')
>>> len(tmp)
852

with bz2.open('debug.tsv.bz2', mode='rt') as f:
...     tmp = f.readline().strip('\r\n').split('\t')
>>> len(tmp)
852

**Comment by piskvorky** [comment] 2019-11-30 10:09
Why are you opening binary files in text mode (`mode='r'`)?

**Comment by mpenkov** [comment] 2019-11-30 11:06
I think this is a duplicate of https://github.com/RaRe-Technologies/smart_open/issues/269

**Comment by yunjiangster** [comment] 2019-11-30 17:46
> Is it OK to open binary files in text mode (`mode='r'`) and without encoding?
> 
> Neither of your outputs (444 and 852) seem to match the line length of your example (7). I don't understand what you're trying to show.

 Two different examples. The input contains special tokens so I quoted an excerpt of the binary representation.

**Comment by yunjiangster** [comment] 2019-11-30 17:47
> I think this is a duplicate of #269

I think the culprit here is the vertical tab character \x0b. Not sure why it gets confused with the line return character.

**Comment by piskvorky** [comment] 2019-11-30 17:54
Please post a fully reproducible example.

**Closed** 2021-01-18 05:46 UTC
Labels: need-info
