### ISSUE TITLE
file_smart_open missing mode 'rb' caused error

### ISSUE THREAD

**Issue by cosmoschen94** [RaRe-Technologies/smart_open#159] opened 2017-12-16 18:49 UTC
Line 668 in `def file_smart_open(fname, mode='rb', encoding=None, errors=DEFAULT_ERRORS)` in smart_open_lib.py

```
try:  # TODO need to fix this place (for cases with r+ and so on)
        raw_mode = {'r': 'rb', 'w': 'wb', 'a': 'ab'}[mode]
except KeyError:
        raw_mode = mode
```

Should include r+ cases. Otherwise, when mode == 'rb', this will cause KeyError

**Comment by mpenkov** [comment] 2017-12-17 05:47
Thank you for reporting this, but I'm not sure what the issue is here. If mode is rb, then a KeyError _is_ raised, but it gets caught immediately below.

Reading files in binary mode also works as expected:

```
(smartopen)sergeyich:smart_open misha$ python
Python 3.6.3 (default, Oct  4 2017, 06:09:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import smart_open
>>> fin = smart_open.smart_open('setup.py', 'rb')
>>> binary = fin.read()
>>> repr(binary[:10])
"b'#!/usr/bin'"
```

Could you please clarify what the problem is? What error are you seeing, and what exactly are you doing to cause that error?

**Comment by cosmoschen94** [comment] 2017-12-17 19:00
I was trying to load a pickle file from my local file system by using 
`model = KeyedVectors.load('input_model.p', mmap='r')`
and this then KeyError was caught, which prevents me from loading the model

**Comment by cosmoschen94** [comment] 2017-12-17 19:01
after I changed 
`raw_mode = {'r': 'rb', 'w': 'wb', 'a': 'ab'}[mode]` to `raw_mode = {'r': 'rb', 'rb':'rb', 'w': 'wb', 'a': 'ab'}[mode]`
I was able to load the model

**Comment by mpenkov** [comment] 2017-12-18 01:42
Thank you for providing us more details.

What is KeyedVectors? It isn't part of the smart_open library, from what I know. How is your code using smart_open?

The KeyError should definitely be caught... Could you please paste your relevant code, and the full stack trace here?

**Comment by menshikh-iv** [comment] 2017-12-18 06:35
@mpenkov KeyedVector is class from gensim that used for storing *2vec vectors ([code](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/keyedvectors.py#L1068))

Need to test this part more carefully and investigate this problem.
Thanks for report @cosmoschen94, can you share your `input_model.p` file with us (for reproducing your error)?

**Comment by menshikh-iv** [comment] 2017-12-21 11:03
I tried to reproduce this (for `py27` and `py36` versions), but I see no bug, everything is working fine.

```
versions:

smart-open==1.5.5
gensim==3.2.0
```


```python
import gensim.downloader as api

model = api.load("glove-twitter-25")
model.most_similar("hello")  # works fine


# save model
model.save("input_model.p")

# load without mmap
loaded_model = model.load("input_model.p")
loaded_model.most_similar("hello")  # works fine


# load with mmap
loaded_model = model.load("input_model.p", mmap="r")
loaded_model.most_similar("hello")  # works fine
```
For this reason, I close this issue.

**Closed by menshikh-iv** 2017-12-21 11:03 UTC
