### ISSUE TITLE
Opening a blob using a BlobClient fails

### ISSUE THREAD

**Issue by TonyBjerstedtTR** [RaRe-Technologies/smart_open#694] opened 2022-04-22 19:13 UTC
#### Problem description

We need to transfer large files between Azure and AWS and are using **smart_open** to create a stream that can be passed to the AWS `boto3` multipart upload method. This will be run in an Azure function triggered by an EventGridEvent which supplies the URL of the Azure blob we wish to send to AWS.

We want to use a ``BlobClient` to manage access to the blob. When we use this client, the `smart_open.open` method throws an exception stating:

> Exception has occurred: AttributeError
> 'BlobClient' object has no attribute 'get_container_client'
> File "C:\projects\test\smotest\download.py", line 13, in main
>    with smart_open.open(path, 'rb', transport_params=dict(client=client)) as stream:
>  File "C:\projects\test\smotest\download.py", line 18, in <module>
>    main()

#### Steps/code to reproduce the problem

The code below will generate the exception shown above:

```python
import os
import smart_open
from azure.storage.blob import BlobClient

URI = 'https://<*storage-acct-goes-here*>.blob.core.windows.net/<*container*>/<*rest-of-the-path*>'
def main():
    client = BlobClient.from_blob_url(URI, os.environ['STORAGE_ACCOUNT_KEY'])

    path = str(f'azure://{client.container_name}/{client.blob_name}')
    with smart_open.open(path, 'rb', transport_params=dict(client=client)) as stream:
        pass

if __name__ == '__main__':
    main()
```

#### Versions

```python
import platform, sys, smart_open
print(platform.platform())
print("Python", sys.version)
print("smart_open", smart_open.__version__)
```
displays:
> Windows-10-10.0.19044-SP0
> Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
> smart_open 5.2.1

**Comment by TonyBjerstedtTR** [comment] 2022-04-26 16:23
upgraded **smart-open** from 5.2.1 to 6.0.0. Passing a `BlobClient` instead of a `BlobServiceClient` now appears to work correctly.

**Comment by mpenkov** [comment] 2022-04-27 00:08
Glad to hear the problem is solved, closing.

**Closed by mpenkov** 2022-04-27 00:08 UTC
