### ISSUE TITLE
Obsolete log in smart_lib_opener

### ISSUE THREAD

**Issue by AvivAvital2** [RaRe-Technologies/smart_open#519] opened 2020-07-08 15:20 UTC
Using the example from the Readme, the following code works as expected.

```python
from smart_open import open as smart_open
import pandas as pd

def cloud_file(azure_storage_connection_string):
    client = BlobServiceClient.from_connection_string(azure_storage_connection_string)
    return smart_open(uri, 'rb', transport_params=dict(client=client))

df = pd.read_csv(cloud_file(azure_storage_connection_string))
```

However, also getting the following log: `CRITICAL:smart_open.smart_open_lib:TODO`  (Found on v2.0.0, v2.1.0)
Is the code above missing anything or can [this](https://github.com/RaRe-Technologies/smart_open/blob/develop/smart_open/smart_open_lib.py#L403) log line be removed?

Thanks

**Comment by petedannemann** [comment] 2020-07-09 15:44
Duplicate of https://github.com/RaRe-Technologies/smart_open/issues/512

**Closed** 2020-10-01 08:55 UTC
