### ISSUE TITLE
`.tell()` on write stream fails with `UnsupportedOperation` in `4.1.2` but not in `3.0.0`

### ISSUE THREAD

**Issue by thesmith** [RaRe-Technologies/smart_open#584] opened 2021-02-13 11:22 UTC
The following code (condensed) works with `smart_open` 3.0.0 but fails with `UnsupportedOperation` in 4.1.2:

```python
with open(s3_uri, 'w', transport_params=self.__transport_params) as fout:
    offset = fout.tell()
    fout.write('{}\n'.format(json.dumps(some_data)))
```

This is really used in a loop so I can record at what offset each json line is written. This means I can seek to it easily again in the future if I read the file.

**Comment by mpenkov** [comment] 2021-02-15 02:31
Duplicate of https://github.com/RaRe-Technologies/smart_open/issues/581

**Closed by mpenkov** 2021-02-15 02:31 UTC
