### ISSUE TITLE
S3 readline doesn't accept other line terminator than `\n`

### ISSUE THREAD

**Issue by lucastamoios** [RaRe-Technologies/smart_open#390] opened 2019-11-14 17:25 UTC
#### Problem description

When trying to read from a file with newlines `\r` the `s3.readline` method doesn't work correctly. The correct behavior would be having in the interface a way to set the line terminator to be universal, like described in the [PEP 0278](https://www.python.org/dev/peps/pep-0278/).

When we try to open a file with `\r` as line break we get the error:

    Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?

#### Steps/code to reproduce the problem

Put some file in the AWS with `\r` as line break and try to iterate over it.

#### Versions

```
Linux-4.15.0-70-generic-x86_64-with-debian-stretch-sid
Python 3.7.2 (default, Dec 28 2018, 11:15:01) 
[GCC 5.4.0 20160609]
smart_open 1.8.4
```

#### Checklist

Before you create the issue, please make sure you have:

- [x] Described the problem clearly
- [x] Provided a minimal reproducible example, including any required data
- [x] Provided the version numbers of the relevant software

**Comment by mpenkov** [comment] 2019-11-15 02:59
Thank you for reporting this. 

Can you show how you're opening the file? The error you reported (new-line character seen in unquoted field) suggests some sort of CSV reading.

**Comment by lucastamoios** [comment] 2019-11-18 13:56
I am using this:
```python
# resource_kwargs have access key and access secrett
with smart_open.s3.open(bucket_id=bucket, key_id=key, mode="rb", resource_kwargs=resource_kwargs) as stream:
    iterate_over_stream(stream)
```

**Comment by mpenkov** [comment] 2019-11-18 15:36
It's not possible for me to reproduce your problem without seeing what you're doing in the `iterate_over_stream` function.

I've tried to reproduce it here, and failed:

```python
In [12]: with open('s3://smart-open-versioned/lineterminator-r.txt', 'r', transport_params={'session': session}) as fin:
    ...:     for line in fin: print(repr(line))
'this\r'
'is\r'
'a\r'
'test'

In [13]: 
```

**Comment by mpenkov** [comment] 2022-04-24 06:33
Could not reproduce, so closing.

**Closed by mpenkov** 2022-04-24 06:33 UTC
