### ISSUE TITLE
Bug in gzipstreamfile

### ISSUE THREAD

**Issue by jfoster17** [RaRe-Technologies/smart_open#84] opened 2016-07-27 19:04 UTC
I ran into a bug while trying to stream a fairly large line of data from a gzipped S3 file. Basically:

    if len(self.unused_buffer) > size:
        return self.read_from_buffer()

is an incorrect call of `read_from_buffer`, which needs to have the argument `size`. I think the correct fix is as simple as:

    if len(self.unused_buffer) > size:
        return self.read_from_buffer(size)

This seems to work in my particular case. Not 100% sure this is the generally correct solution, which if why I'm posting this issue rather than making a PR.

**Comment by mpenkov** [comment] 2016-07-30 06:38
@jfoster17 I can see that the problem is that the statement returns the full contents of the buffer, meaning the read function could theoretically return more bytes than requested. Your proposed solution seems reasonable, but could you be a bit more specific: how did the bug manifest itself in your case? Was it an exception of some sort?

The reason I ask is that I'm trying to reproduce the problem in a unit test, and haven't been able to trigger the problem condition so far.

**Comment by mpenkov** [comment] 2016-07-31 05:22
@jfoster17 Never mind, I reproduced the problem and am working on the fix.

**Comment by tmylk** [comment] 2016-09-18 13:44
Fixed in https://github.com/RaRe-Technologies/smart_open/commit/eba107ff82f1720aea2dabd8cceeadb70dc30611

**Closed by tmylk** 2016-09-18 13:44 UTC
Labels: bug
